CREATE TABLE player
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email     VARCHAR,
    gender    VARCHAR,
    password  VARCHAR,
    name      varchar,
    role      VARCHAR,
    is_active boolean
);