CREATE TABLE step
(
    id      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cows    INT,
    bulls   INT,
    answer  INT,
    time    TIMESTAMP,
    game_id BIGINT,
    CONSTRAINT fk_step_on_game FOREIGN KEY (game_id) REFERENCES game(id)
);